language: node_js
node_js:
  - '12'

env:
  - NODE_PORT=8000

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: 'first-ts-api'
  env: 'Firsttsapi-env'
  skip_cleanup: true

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: 'first-ts-api-bucket'

  bucket_path: 'docker'

  on:
    branch: master
